"""empty message

Revision ID: 00001
Revises:
Create Date: 2026-02-17 07:02:15.416694

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "00001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "brands",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_index(
        op.f("ix_brands_created_at"), "brands", ["created_at"], unique=False
    )
    op.alter_column(
        "categories",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_index(
        op.f("ix_categories_created_at"), "categories", ["created_at"], unique=False
    )
    op.alter_column(
        "product_categories",
        "product_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "product_categories",
        "category_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_product_categories_created_at"),
        "product_categories",
        ["created_at"],
        unique=False,
    )
    op.alter_column(
        "products",
        "id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "brand_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_products_created_at"), "products", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_created_at"), table_name="products")
    op.alter_column(
        "products",
        "brand_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    op.alter_column(
        "products",
        "id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_product_categories_created_at"), table_name="product_categories"
    )
    op.alter_column(
        "product_categories",
        "category_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    op.alter_column(
        "product_categories",
        "product_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_categories_created_at"), table_name="categories")
    op.alter_column(
        "categories",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_brands_created_at"), table_name="brands")
    op.alter_column(
        "brands",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
